idf_component_register(
    SRCS
        "ubo_app_main.c"
        "board.c"
        "net.c"
        "client_app.c"
        "input.c"
        "provisioning.c"
        "audio.c"
        "usb_ppp.c"
    INCLUDE_DIRS "."
    REQUIRES
        ubo_lvgl_renderer
        ubo_client_core
        esp_lcd
        esp_lcd_touch
        esp_lcd_touch_ft5x06
        esp_driver_gpio
        esp_driver_i2c
        esp_driver_i2s
        esp_driver_usb_serial_jtag
        esp_codec_dev
        esp_wifi
        esp_event
        esp_netif
        esp_http_server
        dns_server
        nvs_flash
)
