#:kivy 2.3.0
#:import re re

<QRCodeRenderPage>:
  BoxLayout:
    id: pager
    orientation: 'vertical'
    padding: dp(5), dp(5), dp(5), root.padding_bottom
    spacing: dp(2)

    BoxLayout:
      orientation: 'vertical'
      spacing: dp(2)

      QRCodeWidget:
        content: root.value
        size_hint: 1, 1
        height: self.width
        pos_hint: {'left': 0.5, 'top': 1}

      Label:
        text: '\n'.join([i.strip() for i in re.split(r'(.{15}(?:.{0,10}\s|.{10}))', root.label) if i])
        size_hint: 1, None
        height: self.texture_size[1] if root.label else 0
        opacity: 1 if root.label else 0
        font_size: dp(18)
        halign: 'center'
        valign: 'center'
