---
all:
  children:
    ubo_pods:
      hosts:
        ubo-pod-1:
          ansible_host: ubo-development-pod-1
          ansible_user: pi
          ubo_pod_index: 1
        ubo-pod-2:
          ansible_host: ubo-development-pod-2
          ansible_user: pi
          ubo_pod_index: 2
        ubo-pod-3:
          ansible_host: ubo-development-pod-3
          ansible_user: pi
          ubo_pod_index: 3
        ubo-pod-4:
          ansible_host: ubo-development-pod-4
          ansible_user: pi
          ubo_pod_index: 4
      vars:
        ansible_python_interpreter: /usr/bin/python3
