"""Defines the color constants used in the application."""

PRIMARY_COLOR = '#68B7FF'
SECONDARY_COLOR = '#363F4B'
SECONDARY_COLOR_LIGHT = '#ABA7A7'
INFO_COLOR = '#2196F3'
DANGER_COLOR = '#FF3F51'
WARNING_COLOR = '#FFC107'
SUCCESS_COLOR = '#03F7AE'

RUNNING_COLOR = '#008000'
STOPPED_COLOR = '#ffff00'

__all__ = [
    'DANGER_COLOR',
    'INFO_COLOR',
    'PRIMARY_COLOR',
    'RUNNING_COLOR',
    'SECONDARY_COLOR',
    'SECONDARY_COLOR_LIGHT',
    'STOPPED_COLOR',
    'SUCCESS_COLOR',
    'WARNING_COLOR',
]
