#:kivy 2.3.0

<StatusRenderPage>:
  AnchorLayout:
    padding: 0, root.padding_top, 0, root.padding_bottom

    BoxLayout:
      anchor: 'center', 'top'
      orientation: 'vertical'
      padding: dp(50)
      spacing: dp(10)

      BoxLayout:
        orientation: 'horizontal'
        size_hint: 1, 1 if root.icon else None
        height: self.minimum_height if root.icon else 0
        opacity: 1 if root.icon else 0
        Label:
          text: root.icon
          size_hint: 1, None
          text_width: self.width
          height: self.texture_size[1]
          font_size: dp(root.icon_size)
          halign: 'center'

      Label:
        text: root.text
        text_size: self.width, None
        font_size: dp(root.text_font_size)
        halign: 'center'
        valign: 'middle'
        height: self.texture_size[1]
        size_hint: 1, 1
