FROM ubuntu:mantic

ARG DEBIAN_FRONTEND=noninteractive
RUN apt -y update
RUN apt -y install gcc curl git libasound2-dev libcap-dev libegl1 libgl1 libmtdev1 libzbar0 python3 python3-dev file ca-certificates --no-install-recommends --no-install-suggests
RUN curl -LsSf https://astral.sh/uv/install.sh | sh
ENV PATH="${PATH}:/root/.cargo/bin"
ENV UV_PROJECT_ENVIRONMENT=/venv
WORKDIR /ubo-app
ENTRYPOINT ["/bin/bash", "-c", "uv sync --locked && exec bash"]
