FROM ubuntu:mantic

ARG DEBIAN_FRONTEND=noninteractive
RUN apt -y update
RUN apt -y install gcc curl git libasound2-dev libcap-dev libegl1 libgl1 libmtdev1 libzbar0 python3 python3-dev file --no-install-recommends --no-install-suggests
RUN curl -sSL https://install.python-poetry.org | python3 -
ENV PATH="${PATH}:/root/.local/bin"
WORKDIR /ubo-app
ENTRYPOINT ["/bin/bash", "-c", "poetry install --with dev --extras=dev --verbose && exec bash"]
