/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "ubo_client.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(ubo_client_Any, ubo_client_Any, AUTO)


PB_BIND(ubo_client_BoolValue, ubo_client_BoolValue, AUTO)


PB_BIND(ubo_client_DispatchActionRequest, ubo_client_DispatchActionRequest, AUTO)


PB_BIND(ubo_client_DispatchActionResponse, ubo_client_DispatchActionResponse, AUTO)


PB_BIND(ubo_client_SubscribeEventRequest, ubo_client_SubscribeEventRequest, AUTO)


PB_BIND(ubo_client_SubscribeEventResponse, ubo_client_SubscribeEventResponse, AUTO)


PB_BIND(ubo_client_SubscribeStoreRequest, ubo_client_SubscribeStoreRequest, AUTO)


PB_BIND(ubo_client_SubscribeStoreResponse, ubo_client_SubscribeStoreResponse, AUTO)


PB_BIND(ubo_client_KeypadKeyPressAction, ubo_client_KeypadKeyPressAction, AUTO)


PB_BIND(ubo_client_KeypadKeyReleaseAction, ubo_client_KeypadKeyReleaseAction, AUTO)


PB_BIND(ubo_client_AudioToggleMuteStatusAction, ubo_client_AudioToggleMuteStatusAction, AUTO)


PB_BIND(ubo_client_AudioSetVolumeAction, ubo_client_AudioSetVolumeAction, AUTO)


PB_BIND(ubo_client_Action, ubo_client_Action, 2)


PB_BIND(ubo_client_ApplicationScrollEvent, ubo_client_ApplicationScrollEvent, AUTO)


PB_BIND(ubo_client_MenuChooseByIndexEvent, ubo_client_MenuChooseByIndexEvent, AUTO)


PB_BIND(ubo_client_FrameStreamDataEvent, ubo_client_FrameStreamDataEvent, AUTO)


PB_BIND(ubo_client_Event, ubo_client_Event, 2)


PB_BIND(ubo_client_BasicType, ubo_client_BasicType, AUTO)


PB_BIND(ubo_client_MenuItemData, ubo_client_MenuItemData, AUTO)


PB_BIND(ubo_client_StatusIconData, ubo_client_StatusIconData, AUTO)


PB_BIND(ubo_client_ProgressNotificationData, ubo_client_ProgressNotificationData, AUTO)


PB_BIND(ubo_client_StatusBarData, ubo_client_StatusBarData, AUTO)


PB_BIND(ubo_client_StatusBarData_ProgressNotifications, ubo_client_StatusBarData_ProgressNotifications, AUTO)


PB_BIND(ubo_client_StatusBarData_Icons, ubo_client_StatusBarData_Icons, AUTO)


PB_BIND(ubo_client_HomeViewData, ubo_client_HomeViewData, AUTO)


PB_BIND(ubo_client_HomeViewData_MenuItems, ubo_client_HomeViewData_MenuItems, AUTO)


PB_BIND(ubo_client_MenuViewData, ubo_client_MenuViewData, AUTO)


PB_BIND(ubo_client_MenuViewData_ItemsItem, ubo_client_MenuViewData_ItemsItem, AUTO)


PB_BIND(ubo_client_MenuViewData_Items, ubo_client_MenuViewData_Items, AUTO)


PB_BIND(ubo_client_ApplicationViewData, ubo_client_ApplicationViewData, AUTO)


PB_BIND(ubo_client_RenderViewData, ubo_client_RenderViewData, AUTO)


PB_BIND(ubo_client_RenderViewData_PropsValue2, ubo_client_RenderViewData_PropsValue2, AUTO)


PB_BIND(ubo_client_RenderViewData_PropsValue, ubo_client_RenderViewData_PropsValue, AUTO)


PB_BIND(ubo_client_RenderViewData_PropsDict, ubo_client_RenderViewData_PropsDict, AUTO)


PB_BIND(ubo_client_RenderViewData_PropsDict_ItemsEntry, ubo_client_RenderViewData_PropsDict_ItemsEntry, AUTO)


PB_BIND(ubo_client_RenderViewData_Items, ubo_client_RenderViewData_Items, AUTO)


PB_BIND(ubo_client_NotificationViewData, ubo_client_NotificationViewData, AUTO)


PB_BIND(ubo_client_NotificationViewData_ItemsItem, ubo_client_NotificationViewData_ItemsItem, AUTO)


PB_BIND(ubo_client_NotificationViewData_Items, ubo_client_NotificationViewData_Items, AUTO)


PB_BIND(ubo_client_InstructionViewData, ubo_client_InstructionViewData, AUTO)


PB_BIND(ubo_client_PromptViewData, ubo_client_PromptViewData, AUTO)


PB_BIND(ubo_client_PromptViewData_Items, ubo_client_PromptViewData_Items, AUTO)







