/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_UBO_CLIENT_UBO_CLIENT_PB_H_INCLUDED
#define PB_UBO_CLIENT_UBO_CLIENT_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
/* ── Enums the client encodes ──────────────────────────────────────────────── */
typedef enum _ubo_client_Key {
    ubo_client_Key_KEY_UNSPECIFIED = 0,
    ubo_client_Key_KEY_BACK = 1,
    ubo_client_Key_KEY_HOME = 2,
    ubo_client_Key_KEY_UP = 3,
    ubo_client_Key_KEY_DOWN = 4,
    ubo_client_Key_KEY_L1 = 5,
    ubo_client_Key_KEY_L2 = 6,
    ubo_client_Key_KEY_L3 = 7
} ubo_client_Key;

typedef enum _ubo_client_AudioDevice {
    ubo_client_AudioDevice_AUDIO_DEVICE_UNSPECIFIED = 0,
    ubo_client_AudioDevice_AUDIO_DEVICE_INPUT = 1,
    ubo_client_AudioDevice_AUDIO_DEVICE_OUTPUT = 2
} ubo_client_AudioDevice;

/* Struct definitions */
/* ── google well-known types (minimal, wire-compatible) ──────────────────────
 SubscribeStoreResponse.results carries google.protobuf.Any; is_blanked is a
 google.protobuf.BoolValue, and None is encoded as google.protobuf.Empty. We
 decode Any.value positionally (selectors are fixed order) and only read
 Any.type_url as a string to detect the Empty (None) case. */
typedef struct _ubo_client_Any {
    char *type_url;
    pb_bytes_array_t *value;
} ubo_client_Any;

typedef struct _ubo_client_BoolValue {
    bool *value;
} ubo_client_BoolValue;

/* ── store.v1.StoreService request/response messages ───────────────────────── */
typedef struct _ubo_client_DispatchActionRequest {
    struct _ubo_client_Action *action;
} ubo_client_DispatchActionRequest;

typedef struct _ubo_client_DispatchActionResponse {
    char dummy_field;
} ubo_client_DispatchActionResponse;

typedef struct _ubo_client_SubscribeEventRequest {
    pb_size_t events_count;
    struct _ubo_client_Event *events;
} ubo_client_SubscribeEventRequest;

typedef struct _ubo_client_SubscribeEventResponse {
    struct _ubo_client_Event *event;
} ubo_client_SubscribeEventResponse;

typedef struct _ubo_client_SubscribeStoreRequest {
    pb_size_t selectors_count;
    char **selectors;
} ubo_client_SubscribeStoreRequest;

typedef struct _ubo_client_SubscribeStoreResponse {
    pb_size_t results_count;
    struct _ubo_client_Any *results;
} ubo_client_SubscribeStoreResponse;

/* ── Actions the client encodes (trimmed Action oneof) ─────────────────────── */
typedef struct _ubo_client_KeypadKeyPressAction {
    ubo_client_Key *key;
    pb_size_t pressed_keys_count;
    ubo_client_Key *pressed_keys;
} ubo_client_KeypadKeyPressAction;

typedef struct _ubo_client_KeypadKeyReleaseAction {
    ubo_client_Key *key;
    pb_size_t pressed_keys_count;
    ubo_client_Key *pressed_keys;
} ubo_client_KeypadKeyReleaseAction;

typedef struct _ubo_client_AudioToggleMuteStatusAction {
    ubo_client_AudioDevice *device;
} ubo_client_AudioToggleMuteStatusAction;

typedef struct _ubo_client_Action {
    pb_size_t which_action;
    union _ubo_client_Action_action {
        struct _ubo_client_AudioToggleMuteStatusAction *audio_toggle_mute_status_action;
        struct _ubo_client_KeypadKeyPressAction *keypad_key_press_action;
        struct _ubo_client_KeypadKeyReleaseAction *keypad_key_release_action;
    } action;
} ubo_client_Action;

/* ── Events the client decodes (trimmed Event oneof) ───────────────────────── */
typedef struct _ubo_client_ApplicationScrollEvent {
    char *direction;
} ubo_client_ApplicationScrollEvent;

typedef struct _ubo_client_MenuChooseByIndexEvent {
    int64_t *index;
} ubo_client_MenuChooseByIndexEvent;

typedef struct _ubo_client_FrameStreamDataEvent {
    char *stream_id;
    pb_bytes_array_t *data;
    int64_t *width;
    int64_t *height;
} ubo_client_FrameStreamDataEvent;

typedef struct _ubo_client_Event {
    pb_size_t which_event;
    union _ubo_client_Event_event {
        struct _ubo_client_ApplicationScrollEvent *application_scroll_event;
        struct _ubo_client_FrameStreamDataEvent *frame_stream_data_event;
        struct _ubo_client_MenuChooseByIndexEvent *menu_choose_by_index_event;
    } event;
} ubo_client_Event;

/* ── Dynamic value type (used by RenderViewData props) ───────────────────────
 Field NUMBERS match the server's BasicType; names suffixed to dodge C
 keywords (bool/float). */
typedef struct _ubo_client_BasicType {
    pb_size_t which_basic_type;
    union _ubo_client_BasicType_basic_type {
        bool *bool_value;
        pb_bytes_array_t *bytes_value;
        float *float_value;
        int64_t *int64_value;
        char *string_value;
    } basic_type;
} ubo_client_BasicType;

/* ── Shared view types ─────────────────────────────────────────────────────── */
typedef struct _ubo_client_MenuItemData {
    char *key;
    char *label;
    char *icon;
    char *color;
    bool *is_short;
    char *action_id;
    char *background_color;
} ubo_client_MenuItemData;

typedef struct _ubo_client_StatusIconData {
    char *symbol;
    char *color;
} ubo_client_StatusIconData;

typedef struct _ubo_client_ProgressNotificationData {
    char *id;
    float *progress;
    char *color;
} ubo_client_ProgressNotificationData;

typedef struct _ubo_client_StatusBarData {
    char *title;
    bool *is_recording;
    bool *is_replaying;
    bool *is_recording_audio;
    struct _ubo_client_StatusBarData_ProgressNotifications *progress_notifications;
    char *clock;
    float *temperature;
    float *light_level;
    struct _ubo_client_StatusBarData_Icons *icons;
} ubo_client_StatusBarData;

typedef struct _ubo_client_StatusBarData_ProgressNotifications {
    pb_size_t items_count;
    struct _ubo_client_ProgressNotificationData *items;
} ubo_client_StatusBarData_ProgressNotifications;

typedef struct _ubo_client_StatusBarData_Icons {
    pb_size_t items_count;
    struct _ubo_client_StatusIconData *items;
} ubo_client_StatusBarData_Icons;

/* ── ViewData variants ─────────────────────────────────────────────────────── */
typedef struct _ubo_client_HomeViewData {
    char *type;
    bool *show_status_bar;
    struct _ubo_client_HomeViewData_MenuItems *menu_items;
    float *cpu_percent;
    float *ram_percent;
    float *volume_level;
} ubo_client_HomeViewData;

typedef struct _ubo_client_HomeViewData_MenuItems {
    pb_size_t items_count;
    struct _ubo_client_MenuItemData *items;
} ubo_client_HomeViewData_MenuItems;

typedef struct _ubo_client_MenuViewData {
    char *type;
    bool *show_status_bar;
    char *title;
    char *heading;
    char *sub_heading;
    struct _ubo_client_MenuViewData_Items *items;
    char *placeholder;
    int64_t *page_index;
    int64_t *total_pages;
    int64_t *stack_depth;
} ubo_client_MenuViewData;

typedef struct _ubo_client_MenuViewData_ItemsItem {
    struct _ubo_client_MenuItemData *items;
} ubo_client_MenuViewData_ItemsItem;

typedef struct _ubo_client_MenuViewData_Items {
    pb_size_t items_count;
    struct _ubo_client_MenuViewData_ItemsItem *items;
} ubo_client_MenuViewData_Items;

typedef struct _ubo_client_ApplicationViewData {
    char *type;
    bool *show_status_bar;
    char *application_id;
    /* field 5 (extra_data map) intentionally omitted — unused by the client. */
    int64_t *stack_depth;
} ubo_client_ApplicationViewData;

typedef struct _ubo_client_RenderViewData {
    char *type;
    bool *show_status_bar;
    char *kind;
    char *title;
    struct _ubo_client_RenderViewData_PropsDict *props;
    struct _ubo_client_RenderViewData_Items *items;
    char *stream_id;
    int64_t *stack_depth;
} ubo_client_RenderViewData;

typedef struct _ubo_client_RenderViewData_PropsValue2 {
    pb_size_t items_count;
    struct _ubo_client_BasicType *items;
} ubo_client_RenderViewData_PropsValue2;

typedef struct _ubo_client_RenderViewData_PropsValue {
    pb_size_t which_props_value;
    union _ubo_client_RenderViewData_PropsValue_props_value {
        struct _ubo_client_BasicType *basic_type;
        struct _ubo_client_RenderViewData_PropsValue2 *list;
    } props_value;
} ubo_client_RenderViewData_PropsValue;

typedef struct _ubo_client_RenderViewData_PropsDict {
    pb_size_t items_count;
    struct _ubo_client_RenderViewData_PropsDict_ItemsEntry *items;
} ubo_client_RenderViewData_PropsDict;

typedef struct _ubo_client_RenderViewData_PropsDict_ItemsEntry {
    char *key;
    struct _ubo_client_RenderViewData_PropsValue *value;
} ubo_client_RenderViewData_PropsDict_ItemsEntry;

typedef struct _ubo_client_RenderViewData_Items {
    pb_size_t items_count;
    struct _ubo_client_MenuItemData *items;
} ubo_client_RenderViewData_Items;

typedef struct _ubo_client_NotificationViewData {
    char *type;
    bool *show_status_bar;
    char *notification_id;
    char *title;
    char *content;
    char *icon;
    char *color;
    struct _ubo_client_NotificationViewData_Items *items;
    char *extra_information;
    int64_t *page_index;
    int64_t *total_pages;
    int64_t *stack_depth;
} ubo_client_NotificationViewData;

typedef struct _ubo_client_NotificationViewData_ItemsItem {
    struct _ubo_client_MenuItemData *items;
} ubo_client_NotificationViewData_ItemsItem;

typedef struct _ubo_client_NotificationViewData_Items {
    pb_size_t items_count;
    struct _ubo_client_NotificationViewData_ItemsItem *items;
} ubo_client_NotificationViewData_Items;

typedef struct _ubo_client_InstructionViewData {
    char *type;
    bool *show_status_bar;
    char *title;
    char *instruction;
    char *icon;
    bool *spinner;
    int64_t *timeout_seconds;
    char *progress_text;
    char *footer_text;
    int64_t *stack_depth;
} ubo_client_InstructionViewData;

typedef struct _ubo_client_PromptViewData {
    char *type;
    bool *show_status_bar;
    char *title;
    char *prompt;
    char *icon;
    struct _ubo_client_PromptViewData_Items *items;
    int64_t *stack_depth;
} ubo_client_PromptViewData;

typedef struct _ubo_client_PromptViewData_Items {
    pb_size_t items_count;
    struct _ubo_client_MenuItemData *items;
} ubo_client_PromptViewData_Items;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _ubo_client_Key_MIN ubo_client_Key_KEY_UNSPECIFIED
#define _ubo_client_Key_MAX ubo_client_Key_KEY_L3
#define _ubo_client_Key_ARRAYSIZE ((ubo_client_Key)(ubo_client_Key_KEY_L3+1))

#define _ubo_client_AudioDevice_MIN ubo_client_AudioDevice_AUDIO_DEVICE_UNSPECIFIED
#define _ubo_client_AudioDevice_MAX ubo_client_AudioDevice_AUDIO_DEVICE_OUTPUT
#define _ubo_client_AudioDevice_ARRAYSIZE ((ubo_client_AudioDevice)(ubo_client_AudioDevice_AUDIO_DEVICE_OUTPUT+1))









#define ubo_client_KeypadKeyPressAction_key_ENUMTYPE ubo_client_Key
#define ubo_client_KeypadKeyPressAction_pressed_keys_ENUMTYPE ubo_client_Key

#define ubo_client_KeypadKeyReleaseAction_key_ENUMTYPE ubo_client_Key
#define ubo_client_KeypadKeyReleaseAction_pressed_keys_ENUMTYPE ubo_client_Key

#define ubo_client_AudioToggleMuteStatusAction_device_ENUMTYPE ubo_client_AudioDevice
































/* Initializer values for message structs */
#define ubo_client_Any_init_default              {NULL, NULL}
#define ubo_client_BoolValue_init_default        {NULL}
#define ubo_client_DispatchActionRequest_init_default {NULL}
#define ubo_client_DispatchActionResponse_init_default {0}
#define ubo_client_SubscribeEventRequest_init_default {0, NULL}
#define ubo_client_SubscribeEventResponse_init_default {NULL}
#define ubo_client_SubscribeStoreRequest_init_default {0, NULL}
#define ubo_client_SubscribeStoreResponse_init_default {0, NULL}
#define ubo_client_KeypadKeyPressAction_init_default {NULL, 0, NULL}
#define ubo_client_KeypadKeyReleaseAction_init_default {NULL, 0, NULL}
#define ubo_client_AudioToggleMuteStatusAction_init_default {NULL}
#define ubo_client_Action_init_default           {0, {NULL}}
#define ubo_client_ApplicationScrollEvent_init_default {NULL}
#define ubo_client_MenuChooseByIndexEvent_init_default {NULL}
#define ubo_client_FrameStreamDataEvent_init_default {NULL, NULL, NULL, NULL}
#define ubo_client_Event_init_default            {0, {NULL}}
#define ubo_client_BasicType_init_default        {0, {NULL}}
#define ubo_client_MenuItemData_init_default     {NULL, NULL, NULL, NULL, NULL, NULL, NULL}
#define ubo_client_StatusIconData_init_default   {NULL, NULL}
#define ubo_client_ProgressNotificationData_init_default {NULL, NULL, NULL}
#define ubo_client_StatusBarData_init_default    {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL}
#define ubo_client_StatusBarData_ProgressNotifications_init_default {0, NULL}
#define ubo_client_StatusBarData_Icons_init_default {0, NULL}
#define ubo_client_HomeViewData_init_default     {NULL, NULL, NULL, NULL, NULL, NULL}
#define ubo_client_HomeViewData_MenuItems_init_default {0, NULL}
#define ubo_client_MenuViewData_init_default     {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL}
#define ubo_client_MenuViewData_ItemsItem_init_default {NULL}
#define ubo_client_MenuViewData_Items_init_default {0, NULL}
#define ubo_client_ApplicationViewData_init_default {NULL, NULL, NULL, NULL}
#define ubo_client_RenderViewData_init_default   {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL}
#define ubo_client_RenderViewData_PropsValue2_init_default {0, NULL}
#define ubo_client_RenderViewData_PropsValue_init_default {0, {NULL}}
#define ubo_client_RenderViewData_PropsDict_init_default {0, NULL}
#define ubo_client_RenderViewData_PropsDict_ItemsEntry_init_default {NULL, NULL}
#define ubo_client_RenderViewData_Items_init_default {0, NULL}
#define ubo_client_NotificationViewData_init_default {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL}
#define ubo_client_NotificationViewData_ItemsItem_init_default {NULL}
#define ubo_client_NotificationViewData_Items_init_default {0, NULL}
#define ubo_client_InstructionViewData_init_default {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL}
#define ubo_client_PromptViewData_init_default   {NULL, NULL, NULL, NULL, NULL, NULL, NULL}
#define ubo_client_PromptViewData_Items_init_default {0, NULL}
#define ubo_client_Any_init_zero                 {NULL, NULL}
#define ubo_client_BoolValue_init_zero           {NULL}
#define ubo_client_DispatchActionRequest_init_zero {NULL}
#define ubo_client_DispatchActionResponse_init_zero {0}
#define ubo_client_SubscribeEventRequest_init_zero {0, NULL}
#define ubo_client_SubscribeEventResponse_init_zero {NULL}
#define ubo_client_SubscribeStoreRequest_init_zero {0, NULL}
#define ubo_client_SubscribeStoreResponse_init_zero {0, NULL}
#define ubo_client_KeypadKeyPressAction_init_zero {NULL, 0, NULL}
#define ubo_client_KeypadKeyReleaseAction_init_zero {NULL, 0, NULL}
#define ubo_client_AudioToggleMuteStatusAction_init_zero {NULL}
#define ubo_client_Action_init_zero              {0, {NULL}}
#define ubo_client_ApplicationScrollEvent_init_zero {NULL}
#define ubo_client_MenuChooseByIndexEvent_init_zero {NULL}
#define ubo_client_FrameStreamDataEvent_init_zero {NULL, NULL, NULL, NULL}
#define ubo_client_Event_init_zero               {0, {NULL}}
#define ubo_client_BasicType_init_zero           {0, {NULL}}
#define ubo_client_MenuItemData_init_zero        {NULL, NULL, NULL, NULL, NULL, NULL, NULL}
#define ubo_client_StatusIconData_init_zero      {NULL, NULL}
#define ubo_client_ProgressNotificationData_init_zero {NULL, NULL, NULL}
#define ubo_client_StatusBarData_init_zero       {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL}
#define ubo_client_StatusBarData_ProgressNotifications_init_zero {0, NULL}
#define ubo_client_StatusBarData_Icons_init_zero {0, NULL}
#define ubo_client_HomeViewData_init_zero        {NULL, NULL, NULL, NULL, NULL, NULL}
#define ubo_client_HomeViewData_MenuItems_init_zero {0, NULL}
#define ubo_client_MenuViewData_init_zero        {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL}
#define ubo_client_MenuViewData_ItemsItem_init_zero {NULL}
#define ubo_client_MenuViewData_Items_init_zero  {0, NULL}
#define ubo_client_ApplicationViewData_init_zero {NULL, NULL, NULL, NULL}
#define ubo_client_RenderViewData_init_zero      {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL}
#define ubo_client_RenderViewData_PropsValue2_init_zero {0, NULL}
#define ubo_client_RenderViewData_PropsValue_init_zero {0, {NULL}}
#define ubo_client_RenderViewData_PropsDict_init_zero {0, NULL}
#define ubo_client_RenderViewData_PropsDict_ItemsEntry_init_zero {NULL, NULL}
#define ubo_client_RenderViewData_Items_init_zero {0, NULL}
#define ubo_client_NotificationViewData_init_zero {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL}
#define ubo_client_NotificationViewData_ItemsItem_init_zero {NULL}
#define ubo_client_NotificationViewData_Items_init_zero {0, NULL}
#define ubo_client_InstructionViewData_init_zero {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL}
#define ubo_client_PromptViewData_init_zero      {NULL, NULL, NULL, NULL, NULL, NULL, NULL}
#define ubo_client_PromptViewData_Items_init_zero {0, NULL}

/* Field tags (for use in manual encoding/decoding) */
#define ubo_client_Any_type_url_tag              1
#define ubo_client_Any_value_tag                 2
#define ubo_client_BoolValue_value_tag           1
#define ubo_client_DispatchActionRequest_action_tag 1
#define ubo_client_SubscribeEventRequest_events_tag 2
#define ubo_client_SubscribeEventResponse_event_tag 1
#define ubo_client_SubscribeStoreRequest_selectors_tag 1
#define ubo_client_SubscribeStoreResponse_results_tag 1
#define ubo_client_KeypadKeyPressAction_key_tag  2
#define ubo_client_KeypadKeyPressAction_pressed_keys_tag 3
#define ubo_client_KeypadKeyReleaseAction_key_tag 2
#define ubo_client_KeypadKeyReleaseAction_pressed_keys_tag 3
#define ubo_client_AudioToggleMuteStatusAction_device_tag 2
#define ubo_client_Action_audio_toggle_mute_status_action_tag 35
#define ubo_client_Action_keypad_key_press_action_tag 115
#define ubo_client_Action_keypad_key_release_action_tag 116
#define ubo_client_ApplicationScrollEvent_direction_tag 2
#define ubo_client_MenuChooseByIndexEvent_index_tag 2
#define ubo_client_FrameStreamDataEvent_stream_id_tag 2
#define ubo_client_FrameStreamDataEvent_data_tag 3
#define ubo_client_FrameStreamDataEvent_width_tag 4
#define ubo_client_FrameStreamDataEvent_height_tag 5
#define ubo_client_Event_application_scroll_event_tag 1
#define ubo_client_Event_frame_stream_data_event_tag 72
#define ubo_client_Event_menu_choose_by_index_event_tag 91
#define ubo_client_BasicType_bool_value_tag      1
#define ubo_client_BasicType_bytes_value_tag     2
#define ubo_client_BasicType_float_value_tag     3
#define ubo_client_BasicType_int64_value_tag     4
#define ubo_client_BasicType_string_value_tag    5
#define ubo_client_MenuItemData_key_tag          2
#define ubo_client_MenuItemData_label_tag        3
#define ubo_client_MenuItemData_icon_tag         4
#define ubo_client_MenuItemData_color_tag        5
#define ubo_client_MenuItemData_is_short_tag     6
#define ubo_client_MenuItemData_action_id_tag    7
#define ubo_client_MenuItemData_background_color_tag 8
#define ubo_client_StatusIconData_symbol_tag     2
#define ubo_client_StatusIconData_color_tag      3
#define ubo_client_ProgressNotificationData_id_tag 2
#define ubo_client_ProgressNotificationData_progress_tag 3
#define ubo_client_ProgressNotificationData_color_tag 4
#define ubo_client_StatusBarData_title_tag       2
#define ubo_client_StatusBarData_is_recording_tag 3
#define ubo_client_StatusBarData_is_replaying_tag 4
#define ubo_client_StatusBarData_is_recording_audio_tag 5
#define ubo_client_StatusBarData_progress_notifications_tag 6
#define ubo_client_StatusBarData_clock_tag       7
#define ubo_client_StatusBarData_temperature_tag 8
#define ubo_client_StatusBarData_light_level_tag 9
#define ubo_client_StatusBarData_icons_tag       10
#define ubo_client_StatusBarData_ProgressNotifications_items_tag 1
#define ubo_client_StatusBarData_Icons_items_tag 1
#define ubo_client_HomeViewData_type_tag         2
#define ubo_client_HomeViewData_show_status_bar_tag 3
#define ubo_client_HomeViewData_menu_items_tag   4
#define ubo_client_HomeViewData_cpu_percent_tag  5
#define ubo_client_HomeViewData_ram_percent_tag  6
#define ubo_client_HomeViewData_volume_level_tag 7
#define ubo_client_HomeViewData_MenuItems_items_tag 1
#define ubo_client_MenuViewData_type_tag         2
#define ubo_client_MenuViewData_show_status_bar_tag 3
#define ubo_client_MenuViewData_title_tag        4
#define ubo_client_MenuViewData_heading_tag      5
#define ubo_client_MenuViewData_sub_heading_tag  6
#define ubo_client_MenuViewData_items_tag        7
#define ubo_client_MenuViewData_placeholder_tag  8
#define ubo_client_MenuViewData_page_index_tag   9
#define ubo_client_MenuViewData_total_pages_tag  10
#define ubo_client_MenuViewData_stack_depth_tag  11
#define ubo_client_MenuViewData_ItemsItem_items_tag 1
#define ubo_client_MenuViewData_Items_items_tag  1
#define ubo_client_ApplicationViewData_type_tag  2
#define ubo_client_ApplicationViewData_show_status_bar_tag 3
#define ubo_client_ApplicationViewData_application_id_tag 4
#define ubo_client_ApplicationViewData_stack_depth_tag 6
#define ubo_client_RenderViewData_type_tag       2
#define ubo_client_RenderViewData_show_status_bar_tag 3
#define ubo_client_RenderViewData_kind_tag       4
#define ubo_client_RenderViewData_title_tag      5
#define ubo_client_RenderViewData_props_tag      6
#define ubo_client_RenderViewData_items_tag      7
#define ubo_client_RenderViewData_stream_id_tag  8
#define ubo_client_RenderViewData_stack_depth_tag 9
#define ubo_client_RenderViewData_PropsValue2_items_tag 1
#define ubo_client_RenderViewData_PropsValue_basic_type_tag 1
#define ubo_client_RenderViewData_PropsValue_list_tag 2
#define ubo_client_RenderViewData_PropsDict_items_tag 1
#define ubo_client_RenderViewData_PropsDict_ItemsEntry_key_tag 1
#define ubo_client_RenderViewData_PropsDict_ItemsEntry_value_tag 2
#define ubo_client_RenderViewData_Items_items_tag 1
#define ubo_client_NotificationViewData_type_tag 2
#define ubo_client_NotificationViewData_show_status_bar_tag 3
#define ubo_client_NotificationViewData_notification_id_tag 4
#define ubo_client_NotificationViewData_title_tag 5
#define ubo_client_NotificationViewData_content_tag 6
#define ubo_client_NotificationViewData_icon_tag 7
#define ubo_client_NotificationViewData_color_tag 8
#define ubo_client_NotificationViewData_items_tag 9
#define ubo_client_NotificationViewData_extra_information_tag 10
#define ubo_client_NotificationViewData_page_index_tag 11
#define ubo_client_NotificationViewData_total_pages_tag 12
#define ubo_client_NotificationViewData_stack_depth_tag 13
#define ubo_client_NotificationViewData_ItemsItem_items_tag 1
#define ubo_client_NotificationViewData_Items_items_tag 1
#define ubo_client_InstructionViewData_type_tag  2
#define ubo_client_InstructionViewData_show_status_bar_tag 3
#define ubo_client_InstructionViewData_title_tag 4
#define ubo_client_InstructionViewData_instruction_tag 5
#define ubo_client_InstructionViewData_icon_tag  6
#define ubo_client_InstructionViewData_spinner_tag 7
#define ubo_client_InstructionViewData_timeout_seconds_tag 8
#define ubo_client_InstructionViewData_progress_text_tag 9
#define ubo_client_InstructionViewData_footer_text_tag 10
#define ubo_client_InstructionViewData_stack_depth_tag 11
#define ubo_client_PromptViewData_type_tag       2
#define ubo_client_PromptViewData_show_status_bar_tag 3
#define ubo_client_PromptViewData_title_tag      4
#define ubo_client_PromptViewData_prompt_tag     5
#define ubo_client_PromptViewData_icon_tag       6
#define ubo_client_PromptViewData_items_tag      7
#define ubo_client_PromptViewData_stack_depth_tag 8
#define ubo_client_PromptViewData_Items_items_tag 1

/* Struct field encoding specification for nanopb */
#define ubo_client_Any_FIELDLIST(X, a) \
X(a, POINTER,  SINGULAR, STRING,   type_url,          1) \
X(a, POINTER,  SINGULAR, BYTES,    value,             2)
#define ubo_client_Any_CALLBACK NULL
#define ubo_client_Any_DEFAULT NULL

#define ubo_client_BoolValue_FIELDLIST(X, a) \
X(a, POINTER,  SINGULAR, BOOL,     value,             1)
#define ubo_client_BoolValue_CALLBACK NULL
#define ubo_client_BoolValue_DEFAULT NULL

#define ubo_client_DispatchActionRequest_FIELDLIST(X, a) \
X(a, POINTER,  OPTIONAL, MESSAGE,  action,            1)
#define ubo_client_DispatchActionRequest_CALLBACK NULL
#define ubo_client_DispatchActionRequest_DEFAULT NULL
#define ubo_client_DispatchActionRequest_action_MSGTYPE ubo_client_Action

#define ubo_client_DispatchActionResponse_FIELDLIST(X, a) \

#define ubo_client_DispatchActionResponse_CALLBACK NULL
#define ubo_client_DispatchActionResponse_DEFAULT NULL

#define ubo_client_SubscribeEventRequest_FIELDLIST(X, a) \
X(a, POINTER,  REPEATED, MESSAGE,  events,            2)
#define ubo_client_SubscribeEventRequest_CALLBACK NULL
#define ubo_client_SubscribeEventRequest_DEFAULT NULL
#define ubo_client_SubscribeEventRequest_events_MSGTYPE ubo_client_Event

#define ubo_client_SubscribeEventResponse_FIELDLIST(X, a) \
X(a, POINTER,  OPTIONAL, MESSAGE,  event,             1)
#define ubo_client_SubscribeEventResponse_CALLBACK NULL
#define ubo_client_SubscribeEventResponse_DEFAULT NULL
#define ubo_client_SubscribeEventResponse_event_MSGTYPE ubo_client_Event

#define ubo_client_SubscribeStoreRequest_FIELDLIST(X, a) \
X(a, POINTER,  REPEATED, STRING,   selectors,         1)
#define ubo_client_SubscribeStoreRequest_CALLBACK NULL
#define ubo_client_SubscribeStoreRequest_DEFAULT NULL

#define ubo_client_SubscribeStoreResponse_FIELDLIST(X, a) \
X(a, POINTER,  REPEATED, MESSAGE,  results,           1)
#define ubo_client_SubscribeStoreResponse_CALLBACK NULL
#define ubo_client_SubscribeStoreResponse_DEFAULT NULL
#define ubo_client_SubscribeStoreResponse_results_MSGTYPE ubo_client_Any

#define ubo_client_KeypadKeyPressAction_FIELDLIST(X, a) \
X(a, POINTER,  SINGULAR, UENUM,    key,               2) \
X(a, POINTER,  REPEATED, UENUM,    pressed_keys,      3)
#define ubo_client_KeypadKeyPressAction_CALLBACK NULL
#define ubo_client_KeypadKeyPressAction_DEFAULT NULL

#define ubo_client_KeypadKeyReleaseAction_FIELDLIST(X, a) \
X(a, POINTER,  SINGULAR, UENUM,    key,               2) \
X(a, POINTER,  REPEATED, UENUM,    pressed_keys,      3)
#define ubo_client_KeypadKeyReleaseAction_CALLBACK NULL
#define ubo_client_KeypadKeyReleaseAction_DEFAULT NULL

#define ubo_client_AudioToggleMuteStatusAction_FIELDLIST(X, a) \
X(a, POINTER,  SINGULAR, UENUM,    device,            2)
#define ubo_client_AudioToggleMuteStatusAction_CALLBACK NULL
#define ubo_client_AudioToggleMuteStatusAction_DEFAULT NULL

#define ubo_client_Action_FIELDLIST(X, a) \
X(a, POINTER,  ONEOF,    MESSAGE,  (action,audio_toggle_mute_status_action,action.audio_toggle_mute_status_action),  35) \
X(a, POINTER,  ONEOF,    MESSAGE,  (action,keypad_key_press_action,action.keypad_key_press_action), 115) \
X(a, POINTER,  ONEOF,    MESSAGE,  (action,keypad_key_release_action,action.keypad_key_release_action), 116)
#define ubo_client_Action_CALLBACK NULL
#define ubo_client_Action_DEFAULT NULL
#define ubo_client_Action_action_audio_toggle_mute_status_action_MSGTYPE ubo_client_AudioToggleMuteStatusAction
#define ubo_client_Action_action_keypad_key_press_action_MSGTYPE ubo_client_KeypadKeyPressAction
#define ubo_client_Action_action_keypad_key_release_action_MSGTYPE ubo_client_KeypadKeyReleaseAction

#define ubo_client_ApplicationScrollEvent_FIELDLIST(X, a) \
X(a, POINTER,  SINGULAR, STRING,   direction,         2)
#define ubo_client_ApplicationScrollEvent_CALLBACK NULL
#define ubo_client_ApplicationScrollEvent_DEFAULT NULL

#define ubo_client_MenuChooseByIndexEvent_FIELDLIST(X, a) \
X(a, POINTER,  SINGULAR, INT64,    index,             2)
#define ubo_client_MenuChooseByIndexEvent_CALLBACK NULL
#define ubo_client_MenuChooseByIndexEvent_DEFAULT NULL

#define ubo_client_FrameStreamDataEvent_FIELDLIST(X, a) \
X(a, POINTER,  SINGULAR, STRING,   stream_id,         2) \
X(a, POINTER,  SINGULAR, BYTES,    data,              3) \
X(a, POINTER,  SINGULAR, INT64,    width,             4) \
X(a, POINTER,  SINGULAR, INT64,    height,            5)
#define ubo_client_FrameStreamDataEvent_CALLBACK NULL
#define ubo_client_FrameStreamDataEvent_DEFAULT NULL

#define ubo_client_Event_FIELDLIST(X, a) \
X(a, POINTER,  ONEOF,    MESSAGE,  (event,application_scroll_event,event.application_scroll_event),   1) \
X(a, POINTER,  ONEOF,    MESSAGE,  (event,frame_stream_data_event,event.frame_stream_data_event),  72) \
X(a, POINTER,  ONEOF,    MESSAGE,  (event,menu_choose_by_index_event,event.menu_choose_by_index_event),  91)
#define ubo_client_Event_CALLBACK NULL
#define ubo_client_Event_DEFAULT NULL
#define ubo_client_Event_event_application_scroll_event_MSGTYPE ubo_client_ApplicationScrollEvent
#define ubo_client_Event_event_frame_stream_data_event_MSGTYPE ubo_client_FrameStreamDataEvent
#define ubo_client_Event_event_menu_choose_by_index_event_MSGTYPE ubo_client_MenuChooseByIndexEvent

#define ubo_client_BasicType_FIELDLIST(X, a) \
X(a, POINTER,  ONEOF,    BOOL,     (basic_type,bool_value,basic_type.bool_value),   1) \
X(a, POINTER,  ONEOF,    BYTES,    (basic_type,bytes_value,basic_type.bytes_value),   2) \
X(a, POINTER,  ONEOF,    FLOAT,    (basic_type,float_value,basic_type.float_value),   3) \
X(a, POINTER,  ONEOF,    INT64,    (basic_type,int64_value,basic_type.int64_value),   4) \
X(a, POINTER,  ONEOF,    STRING,   (basic_type,string_value,basic_type.string_value),   5)
#define ubo_client_BasicType_CALLBACK NULL
#define ubo_client_BasicType_DEFAULT NULL

#define ubo_client_MenuItemData_FIELDLIST(X, a) \
X(a, POINTER,  SINGULAR, STRING,   key,               2) \
X(a, POINTER,  SINGULAR, STRING,   label,             3) \
X(a, POINTER,  SINGULAR, STRING,   icon,              4) \
X(a, POINTER,  OPTIONAL, STRING,   color,             5) \
X(a, POINTER,  OPTIONAL, BOOL,     is_short,          6) \
X(a, POINTER,  OPTIONAL, STRING,   action_id,         7) \
X(a, POINTER,  OPTIONAL, STRING,   background_color,   8)
#define ubo_client_MenuItemData_CALLBACK NULL
#define ubo_client_MenuItemData_DEFAULT NULL

#define ubo_client_StatusIconData_FIELDLIST(X, a) \
X(a, POINTER,  SINGULAR, STRING,   symbol,            2) \
X(a, POINTER,  SINGULAR, STRING,   color,             3)
#define ubo_client_StatusIconData_CALLBACK NULL
#define ubo_client_StatusIconData_DEFAULT NULL

#define ubo_client_ProgressNotificationData_FIELDLIST(X, a) \
X(a, POINTER,  SINGULAR, STRING,   id,                2) \
X(a, POINTER,  OPTIONAL, FLOAT,    progress,          3) \
X(a, POINTER,  SINGULAR, STRING,   color,             4)
#define ubo_client_ProgressNotificationData_CALLBACK NULL
#define ubo_client_ProgressNotificationData_DEFAULT NULL

#define ubo_client_StatusBarData_FIELDLIST(X, a) \
X(a, POINTER,  OPTIONAL, STRING,   title,             2) \
X(a, POINTER,  OPTIONAL, BOOL,     is_recording,      3) \
X(a, POINTER,  OPTIONAL, BOOL,     is_replaying,      4) \
X(a, POINTER,  OPTIONAL, BOOL,     is_recording_audio,   5) \
X(a, POINTER,  OPTIONAL, MESSAGE,  progress_notifications,   6) \
X(a, POINTER,  OPTIONAL, STRING,   clock,             7) \
X(a, POINTER,  OPTIONAL, FLOAT,    temperature,       8) \
X(a, POINTER,  OPTIONAL, FLOAT,    light_level,       9) \
X(a, POINTER,  OPTIONAL, MESSAGE,  icons,            10)
#define ubo_client_StatusBarData_CALLBACK NULL
#define ubo_client_StatusBarData_DEFAULT NULL
#define ubo_client_StatusBarData_progress_notifications_MSGTYPE ubo_client_StatusBarData_ProgressNotifications
#define ubo_client_StatusBarData_icons_MSGTYPE ubo_client_StatusBarData_Icons

#define ubo_client_StatusBarData_ProgressNotifications_FIELDLIST(X, a) \
X(a, POINTER,  REPEATED, MESSAGE,  items,             1)
#define ubo_client_StatusBarData_ProgressNotifications_CALLBACK NULL
#define ubo_client_StatusBarData_ProgressNotifications_DEFAULT NULL
#define ubo_client_StatusBarData_ProgressNotifications_items_MSGTYPE ubo_client_ProgressNotificationData

#define ubo_client_StatusBarData_Icons_FIELDLIST(X, a) \
X(a, POINTER,  REPEATED, MESSAGE,  items,             1)
#define ubo_client_StatusBarData_Icons_CALLBACK NULL
#define ubo_client_StatusBarData_Icons_DEFAULT NULL
#define ubo_client_StatusBarData_Icons_items_MSGTYPE ubo_client_StatusIconData

#define ubo_client_HomeViewData_FIELDLIST(X, a) \
X(a, POINTER,  OPTIONAL, STRING,   type,              2) \
X(a, POINTER,  OPTIONAL, BOOL,     show_status_bar,   3) \
X(a, POINTER,  OPTIONAL, MESSAGE,  menu_items,        4) \
X(a, POINTER,  OPTIONAL, FLOAT,    cpu_percent,       5) \
X(a, POINTER,  OPTIONAL, FLOAT,    ram_percent,       6) \
X(a, POINTER,  OPTIONAL, FLOAT,    volume_level,      7)
#define ubo_client_HomeViewData_CALLBACK NULL
#define ubo_client_HomeViewData_DEFAULT NULL
#define ubo_client_HomeViewData_menu_items_MSGTYPE ubo_client_HomeViewData_MenuItems

#define ubo_client_HomeViewData_MenuItems_FIELDLIST(X, a) \
X(a, POINTER,  REPEATED, MESSAGE,  items,             1)
#define ubo_client_HomeViewData_MenuItems_CALLBACK NULL
#define ubo_client_HomeViewData_MenuItems_DEFAULT NULL
#define ubo_client_HomeViewData_MenuItems_items_MSGTYPE ubo_client_MenuItemData

#define ubo_client_MenuViewData_FIELDLIST(X, a) \
X(a, POINTER,  OPTIONAL, STRING,   type,              2) \
X(a, POINTER,  OPTIONAL, BOOL,     show_status_bar,   3) \
X(a, POINTER,  OPTIONAL, STRING,   title,             4) \
X(a, POINTER,  OPTIONAL, STRING,   heading,           5) \
X(a, POINTER,  OPTIONAL, STRING,   sub_heading,       6) \
X(a, POINTER,  OPTIONAL, MESSAGE,  items,             7) \
X(a, POINTER,  OPTIONAL, STRING,   placeholder,       8) \
X(a, POINTER,  OPTIONAL, INT64,    page_index,        9) \
X(a, POINTER,  OPTIONAL, INT64,    total_pages,      10) \
X(a, POINTER,  OPTIONAL, INT64,    stack_depth,      11)
#define ubo_client_MenuViewData_CALLBACK NULL
#define ubo_client_MenuViewData_DEFAULT NULL
#define ubo_client_MenuViewData_items_MSGTYPE ubo_client_MenuViewData_Items

#define ubo_client_MenuViewData_ItemsItem_FIELDLIST(X, a) \
X(a, POINTER,  OPTIONAL, MESSAGE,  items,             1)
#define ubo_client_MenuViewData_ItemsItem_CALLBACK NULL
#define ubo_client_MenuViewData_ItemsItem_DEFAULT NULL
#define ubo_client_MenuViewData_ItemsItem_items_MSGTYPE ubo_client_MenuItemData

#define ubo_client_MenuViewData_Items_FIELDLIST(X, a) \
X(a, POINTER,  REPEATED, MESSAGE,  items,             1)
#define ubo_client_MenuViewData_Items_CALLBACK NULL
#define ubo_client_MenuViewData_Items_DEFAULT NULL
#define ubo_client_MenuViewData_Items_items_MSGTYPE ubo_client_MenuViewData_ItemsItem

#define ubo_client_ApplicationViewData_FIELDLIST(X, a) \
X(a, POINTER,  OPTIONAL, STRING,   type,              2) \
X(a, POINTER,  OPTIONAL, BOOL,     show_status_bar,   3) \
X(a, POINTER,  OPTIONAL, STRING,   application_id,    4) \
X(a, POINTER,  OPTIONAL, INT64,    stack_depth,       6)
#define ubo_client_ApplicationViewData_CALLBACK NULL
#define ubo_client_ApplicationViewData_DEFAULT NULL

#define ubo_client_RenderViewData_FIELDLIST(X, a) \
X(a, POINTER,  OPTIONAL, STRING,   type,              2) \
X(a, POINTER,  OPTIONAL, BOOL,     show_status_bar,   3) \
X(a, POINTER,  OPTIONAL, STRING,   kind,              4) \
X(a, POINTER,  OPTIONAL, STRING,   title,             5) \
X(a, POINTER,  OPTIONAL, MESSAGE,  props,             6) \
X(a, POINTER,  OPTIONAL, MESSAGE,  items,             7) \
X(a, POINTER,  OPTIONAL, STRING,   stream_id,         8) \
X(a, POINTER,  OPTIONAL, INT64,    stack_depth,       9)
#define ubo_client_RenderViewData_CALLBACK NULL
#define ubo_client_RenderViewData_DEFAULT NULL
#define ubo_client_RenderViewData_props_MSGTYPE ubo_client_RenderViewData_PropsDict
#define ubo_client_RenderViewData_items_MSGTYPE ubo_client_RenderViewData_Items

#define ubo_client_RenderViewData_PropsValue2_FIELDLIST(X, a) \
X(a, POINTER,  REPEATED, MESSAGE,  items,             1)
#define ubo_client_RenderViewData_PropsValue2_CALLBACK NULL
#define ubo_client_RenderViewData_PropsValue2_DEFAULT NULL
#define ubo_client_RenderViewData_PropsValue2_items_MSGTYPE ubo_client_BasicType

#define ubo_client_RenderViewData_PropsValue_FIELDLIST(X, a) \
X(a, POINTER,  ONEOF,    MESSAGE,  (props_value,basic_type,props_value.basic_type),   1) \
X(a, POINTER,  ONEOF,    MESSAGE,  (props_value,list,props_value.list),   2)
#define ubo_client_RenderViewData_PropsValue_CALLBACK NULL
#define ubo_client_RenderViewData_PropsValue_DEFAULT NULL
#define ubo_client_RenderViewData_PropsValue_props_value_basic_type_MSGTYPE ubo_client_BasicType
#define ubo_client_RenderViewData_PropsValue_props_value_list_MSGTYPE ubo_client_RenderViewData_PropsValue2

#define ubo_client_RenderViewData_PropsDict_FIELDLIST(X, a) \
X(a, POINTER,  REPEATED, MESSAGE,  items,             1)
#define ubo_client_RenderViewData_PropsDict_CALLBACK NULL
#define ubo_client_RenderViewData_PropsDict_DEFAULT NULL
#define ubo_client_RenderViewData_PropsDict_items_MSGTYPE ubo_client_RenderViewData_PropsDict_ItemsEntry

#define ubo_client_RenderViewData_PropsDict_ItemsEntry_FIELDLIST(X, a) \
X(a, POINTER,  SINGULAR, STRING,   key,               1) \
X(a, POINTER,  OPTIONAL, MESSAGE,  value,             2)
#define ubo_client_RenderViewData_PropsDict_ItemsEntry_CALLBACK NULL
#define ubo_client_RenderViewData_PropsDict_ItemsEntry_DEFAULT NULL
#define ubo_client_RenderViewData_PropsDict_ItemsEntry_value_MSGTYPE ubo_client_RenderViewData_PropsValue

#define ubo_client_RenderViewData_Items_FIELDLIST(X, a) \
X(a, POINTER,  REPEATED, MESSAGE,  items,             1)
#define ubo_client_RenderViewData_Items_CALLBACK NULL
#define ubo_client_RenderViewData_Items_DEFAULT NULL
#define ubo_client_RenderViewData_Items_items_MSGTYPE ubo_client_MenuItemData

#define ubo_client_NotificationViewData_FIELDLIST(X, a) \
X(a, POINTER,  OPTIONAL, STRING,   type,              2) \
X(a, POINTER,  OPTIONAL, BOOL,     show_status_bar,   3) \
X(a, POINTER,  OPTIONAL, STRING,   notification_id,   4) \
X(a, POINTER,  OPTIONAL, STRING,   title,             5) \
X(a, POINTER,  OPTIONAL, STRING,   content,           6) \
X(a, POINTER,  OPTIONAL, STRING,   icon,              7) \
X(a, POINTER,  OPTIONAL, STRING,   color,             8) \
X(a, POINTER,  OPTIONAL, MESSAGE,  items,             9) \
X(a, POINTER,  OPTIONAL, STRING,   extra_information,  10) \
X(a, POINTER,  OPTIONAL, INT64,    page_index,       11) \
X(a, POINTER,  OPTIONAL, INT64,    total_pages,      12) \
X(a, POINTER,  OPTIONAL, INT64,    stack_depth,      13)
#define ubo_client_NotificationViewData_CALLBACK NULL
#define ubo_client_NotificationViewData_DEFAULT NULL
#define ubo_client_NotificationViewData_items_MSGTYPE ubo_client_NotificationViewData_Items

#define ubo_client_NotificationViewData_ItemsItem_FIELDLIST(X, a) \
X(a, POINTER,  OPTIONAL, MESSAGE,  items,             1)
#define ubo_client_NotificationViewData_ItemsItem_CALLBACK NULL
#define ubo_client_NotificationViewData_ItemsItem_DEFAULT NULL
#define ubo_client_NotificationViewData_ItemsItem_items_MSGTYPE ubo_client_MenuItemData

#define ubo_client_NotificationViewData_Items_FIELDLIST(X, a) \
X(a, POINTER,  REPEATED, MESSAGE,  items,             1)
#define ubo_client_NotificationViewData_Items_CALLBACK NULL
#define ubo_client_NotificationViewData_Items_DEFAULT NULL
#define ubo_client_NotificationViewData_Items_items_MSGTYPE ubo_client_NotificationViewData_ItemsItem

#define ubo_client_InstructionViewData_FIELDLIST(X, a) \
X(a, POINTER,  OPTIONAL, STRING,   type,              2) \
X(a, POINTER,  OPTIONAL, BOOL,     show_status_bar,   3) \
X(a, POINTER,  OPTIONAL, STRING,   title,             4) \
X(a, POINTER,  OPTIONAL, STRING,   instruction,       5) \
X(a, POINTER,  OPTIONAL, STRING,   icon,              6) \
X(a, POINTER,  OPTIONAL, BOOL,     spinner,           7) \
X(a, POINTER,  OPTIONAL, INT64,    timeout_seconds,   8) \
X(a, POINTER,  OPTIONAL, STRING,   progress_text,     9) \
X(a, POINTER,  OPTIONAL, STRING,   footer_text,      10) \
X(a, POINTER,  OPTIONAL, INT64,    stack_depth,      11)
#define ubo_client_InstructionViewData_CALLBACK NULL
#define ubo_client_InstructionViewData_DEFAULT NULL

#define ubo_client_PromptViewData_FIELDLIST(X, a) \
X(a, POINTER,  OPTIONAL, STRING,   type,              2) \
X(a, POINTER,  OPTIONAL, BOOL,     show_status_bar,   3) \
X(a, POINTER,  OPTIONAL, STRING,   title,             4) \
X(a, POINTER,  OPTIONAL, STRING,   prompt,            5) \
X(a, POINTER,  OPTIONAL, STRING,   icon,              6) \
X(a, POINTER,  OPTIONAL, MESSAGE,  items,             7) \
X(a, POINTER,  OPTIONAL, INT64,    stack_depth,       8)
#define ubo_client_PromptViewData_CALLBACK NULL
#define ubo_client_PromptViewData_DEFAULT NULL
#define ubo_client_PromptViewData_items_MSGTYPE ubo_client_PromptViewData_Items

#define ubo_client_PromptViewData_Items_FIELDLIST(X, a) \
X(a, POINTER,  REPEATED, MESSAGE,  items,             1)
#define ubo_client_PromptViewData_Items_CALLBACK NULL
#define ubo_client_PromptViewData_Items_DEFAULT NULL
#define ubo_client_PromptViewData_Items_items_MSGTYPE ubo_client_MenuItemData

extern const pb_msgdesc_t ubo_client_Any_msg;
extern const pb_msgdesc_t ubo_client_BoolValue_msg;
extern const pb_msgdesc_t ubo_client_DispatchActionRequest_msg;
extern const pb_msgdesc_t ubo_client_DispatchActionResponse_msg;
extern const pb_msgdesc_t ubo_client_SubscribeEventRequest_msg;
extern const pb_msgdesc_t ubo_client_SubscribeEventResponse_msg;
extern const pb_msgdesc_t ubo_client_SubscribeStoreRequest_msg;
extern const pb_msgdesc_t ubo_client_SubscribeStoreResponse_msg;
extern const pb_msgdesc_t ubo_client_KeypadKeyPressAction_msg;
extern const pb_msgdesc_t ubo_client_KeypadKeyReleaseAction_msg;
extern const pb_msgdesc_t ubo_client_AudioToggleMuteStatusAction_msg;
extern const pb_msgdesc_t ubo_client_Action_msg;
extern const pb_msgdesc_t ubo_client_ApplicationScrollEvent_msg;
extern const pb_msgdesc_t ubo_client_MenuChooseByIndexEvent_msg;
extern const pb_msgdesc_t ubo_client_FrameStreamDataEvent_msg;
extern const pb_msgdesc_t ubo_client_Event_msg;
extern const pb_msgdesc_t ubo_client_BasicType_msg;
extern const pb_msgdesc_t ubo_client_MenuItemData_msg;
extern const pb_msgdesc_t ubo_client_StatusIconData_msg;
extern const pb_msgdesc_t ubo_client_ProgressNotificationData_msg;
extern const pb_msgdesc_t ubo_client_StatusBarData_msg;
extern const pb_msgdesc_t ubo_client_StatusBarData_ProgressNotifications_msg;
extern const pb_msgdesc_t ubo_client_StatusBarData_Icons_msg;
extern const pb_msgdesc_t ubo_client_HomeViewData_msg;
extern const pb_msgdesc_t ubo_client_HomeViewData_MenuItems_msg;
extern const pb_msgdesc_t ubo_client_MenuViewData_msg;
extern const pb_msgdesc_t ubo_client_MenuViewData_ItemsItem_msg;
extern const pb_msgdesc_t ubo_client_MenuViewData_Items_msg;
extern const pb_msgdesc_t ubo_client_ApplicationViewData_msg;
extern const pb_msgdesc_t ubo_client_RenderViewData_msg;
extern const pb_msgdesc_t ubo_client_RenderViewData_PropsValue2_msg;
extern const pb_msgdesc_t ubo_client_RenderViewData_PropsValue_msg;
extern const pb_msgdesc_t ubo_client_RenderViewData_PropsDict_msg;
extern const pb_msgdesc_t ubo_client_RenderViewData_PropsDict_ItemsEntry_msg;
extern const pb_msgdesc_t ubo_client_RenderViewData_Items_msg;
extern const pb_msgdesc_t ubo_client_NotificationViewData_msg;
extern const pb_msgdesc_t ubo_client_NotificationViewData_ItemsItem_msg;
extern const pb_msgdesc_t ubo_client_NotificationViewData_Items_msg;
extern const pb_msgdesc_t ubo_client_InstructionViewData_msg;
extern const pb_msgdesc_t ubo_client_PromptViewData_msg;
extern const pb_msgdesc_t ubo_client_PromptViewData_Items_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define ubo_client_Any_fields &ubo_client_Any_msg
#define ubo_client_BoolValue_fields &ubo_client_BoolValue_msg
#define ubo_client_DispatchActionRequest_fields &ubo_client_DispatchActionRequest_msg
#define ubo_client_DispatchActionResponse_fields &ubo_client_DispatchActionResponse_msg
#define ubo_client_SubscribeEventRequest_fields &ubo_client_SubscribeEventRequest_msg
#define ubo_client_SubscribeEventResponse_fields &ubo_client_SubscribeEventResponse_msg
#define ubo_client_SubscribeStoreRequest_fields &ubo_client_SubscribeStoreRequest_msg
#define ubo_client_SubscribeStoreResponse_fields &ubo_client_SubscribeStoreResponse_msg
#define ubo_client_KeypadKeyPressAction_fields &ubo_client_KeypadKeyPressAction_msg
#define ubo_client_KeypadKeyReleaseAction_fields &ubo_client_KeypadKeyReleaseAction_msg
#define ubo_client_AudioToggleMuteStatusAction_fields &ubo_client_AudioToggleMuteStatusAction_msg
#define ubo_client_Action_fields &ubo_client_Action_msg
#define ubo_client_ApplicationScrollEvent_fields &ubo_client_ApplicationScrollEvent_msg
#define ubo_client_MenuChooseByIndexEvent_fields &ubo_client_MenuChooseByIndexEvent_msg
#define ubo_client_FrameStreamDataEvent_fields &ubo_client_FrameStreamDataEvent_msg
#define ubo_client_Event_fields &ubo_client_Event_msg
#define ubo_client_BasicType_fields &ubo_client_BasicType_msg
#define ubo_client_MenuItemData_fields &ubo_client_MenuItemData_msg
#define ubo_client_StatusIconData_fields &ubo_client_StatusIconData_msg
#define ubo_client_ProgressNotificationData_fields &ubo_client_ProgressNotificationData_msg
#define ubo_client_StatusBarData_fields &ubo_client_StatusBarData_msg
#define ubo_client_StatusBarData_ProgressNotifications_fields &ubo_client_StatusBarData_ProgressNotifications_msg
#define ubo_client_StatusBarData_Icons_fields &ubo_client_StatusBarData_Icons_msg
#define ubo_client_HomeViewData_fields &ubo_client_HomeViewData_msg
#define ubo_client_HomeViewData_MenuItems_fields &ubo_client_HomeViewData_MenuItems_msg
#define ubo_client_MenuViewData_fields &ubo_client_MenuViewData_msg
#define ubo_client_MenuViewData_ItemsItem_fields &ubo_client_MenuViewData_ItemsItem_msg
#define ubo_client_MenuViewData_Items_fields &ubo_client_MenuViewData_Items_msg
#define ubo_client_ApplicationViewData_fields &ubo_client_ApplicationViewData_msg
#define ubo_client_RenderViewData_fields &ubo_client_RenderViewData_msg
#define ubo_client_RenderViewData_PropsValue2_fields &ubo_client_RenderViewData_PropsValue2_msg
#define ubo_client_RenderViewData_PropsValue_fields &ubo_client_RenderViewData_PropsValue_msg
#define ubo_client_RenderViewData_PropsDict_fields &ubo_client_RenderViewData_PropsDict_msg
#define ubo_client_RenderViewData_PropsDict_ItemsEntry_fields &ubo_client_RenderViewData_PropsDict_ItemsEntry_msg
#define ubo_client_RenderViewData_Items_fields &ubo_client_RenderViewData_Items_msg
#define ubo_client_NotificationViewData_fields &ubo_client_NotificationViewData_msg
#define ubo_client_NotificationViewData_ItemsItem_fields &ubo_client_NotificationViewData_ItemsItem_msg
#define ubo_client_NotificationViewData_Items_fields &ubo_client_NotificationViewData_Items_msg
#define ubo_client_InstructionViewData_fields &ubo_client_InstructionViewData_msg
#define ubo_client_PromptViewData_fields &ubo_client_PromptViewData_msg
#define ubo_client_PromptViewData_Items_fields &ubo_client_PromptViewData_Items_msg

/* Maximum encoded size of messages (where known) */
/* ubo_client_Any_size depends on runtime parameters */
/* ubo_client_DispatchActionRequest_size depends on runtime parameters */
/* ubo_client_SubscribeEventRequest_size depends on runtime parameters */
/* ubo_client_SubscribeEventResponse_size depends on runtime parameters */
/* ubo_client_SubscribeStoreRequest_size depends on runtime parameters */
/* ubo_client_SubscribeStoreResponse_size depends on runtime parameters */
/* ubo_client_KeypadKeyPressAction_size depends on runtime parameters */
/* ubo_client_KeypadKeyReleaseAction_size depends on runtime parameters */
/* ubo_client_Action_size depends on runtime parameters */
/* ubo_client_ApplicationScrollEvent_size depends on runtime parameters */
/* ubo_client_FrameStreamDataEvent_size depends on runtime parameters */
/* ubo_client_Event_size depends on runtime parameters */
/* ubo_client_BasicType_size depends on runtime parameters */
/* ubo_client_MenuItemData_size depends on runtime parameters */
/* ubo_client_StatusIconData_size depends on runtime parameters */
/* ubo_client_ProgressNotificationData_size depends on runtime parameters */
/* ubo_client_StatusBarData_size depends on runtime parameters */
/* ubo_client_StatusBarData_ProgressNotifications_size depends on runtime parameters */
/* ubo_client_StatusBarData_Icons_size depends on runtime parameters */
/* ubo_client_HomeViewData_size depends on runtime parameters */
/* ubo_client_HomeViewData_MenuItems_size depends on runtime parameters */
/* ubo_client_MenuViewData_size depends on runtime parameters */
/* ubo_client_MenuViewData_ItemsItem_size depends on runtime parameters */
/* ubo_client_MenuViewData_Items_size depends on runtime parameters */
/* ubo_client_ApplicationViewData_size depends on runtime parameters */
/* ubo_client_RenderViewData_size depends on runtime parameters */
/* ubo_client_RenderViewData_PropsValue2_size depends on runtime parameters */
/* ubo_client_RenderViewData_PropsValue_size depends on runtime parameters */
/* ubo_client_RenderViewData_PropsDict_size depends on runtime parameters */
/* ubo_client_RenderViewData_PropsDict_ItemsEntry_size depends on runtime parameters */
/* ubo_client_RenderViewData_Items_size depends on runtime parameters */
/* ubo_client_NotificationViewData_size depends on runtime parameters */
/* ubo_client_NotificationViewData_ItemsItem_size depends on runtime parameters */
/* ubo_client_NotificationViewData_Items_size depends on runtime parameters */
/* ubo_client_InstructionViewData_size depends on runtime parameters */
/* ubo_client_PromptViewData_size depends on runtime parameters */
/* ubo_client_PromptViewData_Items_size depends on runtime parameters */
#define UBO_CLIENT_UBO_CLIENT_PB_H_MAX_SIZE      ubo_client_MenuChooseByIndexEvent_size
#define ubo_client_AudioToggleMuteStatusAction_size 2
#define ubo_client_BoolValue_size                2
#define ubo_client_DispatchActionResponse_size   0
#define ubo_client_MenuChooseByIndexEvent_size   11

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
