name: CI/CD

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:

env:
  PYTHON_VERSION: '3.11.9'

jobs:
  dependencies:
    name: Install Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout

      - name: System Dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y portaudio19-dev

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
          cache-suffix: ubuntu-latest

      - name: Create virtualenv
        run: |
          uv venv --system-site-packages

      - name: Install dependencies
        run: uv sync --frozen

  ubo-pod-dependencies:
    name: Install Ubo Pod Dependencies
    runs-on: ubo-pod-pi5
    outputs:
      python-version: ${{ steps.get-python-version.outputs.PYTHON_VERSION }}
    steps:
      - uses: actions/checkout@v4
        name: Checkout

      - name: Extract Python Version
        id: get-python-version
        run: |
          echo "PYTHON_VERSION=$(python --version | cut -d' ' -f2)" >>$GITHUB_OUTPUT
          echo "PYTHON_VERSION=$(python --version | cut -d' ' -f2)"

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
          cache-suffix: ubo-pod

      - name: Create virtualenv
        run: |
          uv venv --system-site-packages

      - name: Install dependencies
        run: |
          uv sync --frozen

  type-check:
    name: Type Check
    needs:
      - ubo-pod-dependencies
    runs-on: ubo-pod-pi5
    steps:
      - uses: actions/checkout@v4
        name: Checkout

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
          cache-suffix: ubo-pod

      - name: Create virtualenv
        run: |
          uv venv --system-site-packages

      - name: Create stub files
        run: |
          uv run --frozen pyright --createstub kivy

      - name: Type Check
        run: |
          uv run --frozen poe typecheck

  lint:
    name: Lint
    needs:
      - dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
          cache-suffix: ubuntu-latest

      - name: Lint
        run: ip a
