name: Publish to PyPI

on:
  workflow_dispatch:
    inputs:
      run_id:
        description: 'Run ID from CI/CD workflow (check its logs)'
        required: true

jobs:
  publish:
    name: Publish
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    needs:
      - type-check
      - lint
      - test
      - build
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url:
        https://pypi.org/project/${{ needs.build.outputs.name }}/${{
        needs.build.outputs.version }}
    permissions:
      id-token: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: wheel
          path: dist
          run-id: ${{ github.event.inputs.run_id }}

      - uses: actions/download-artifact@v4
        with:
          name: binary
          path: dist
          run-id: ${{ github.event.inputs.run_id }}

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist
