name: Create Release Tag

on:
  pull_request:
    types:
      - closed

jobs:
  create_release_tag:
    runs-on: ubuntu-latest
    if: >-
      github.event_name == 'pull_request' && github.event.action == 'closed' &&
      github.event.pull_request.merged == true &&
      github.event.pull_request.base.ref == 'main' &&
      startsWith(github.event.pull_request.head.ref, 'release/')
    steps:
      - uses: actions/checkout@v4
        name: Checkout
        with:
          lfs: true

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
          cache-suffix: ubuntu-latest

      - name: Extract Version
        id: extract-version
        run: |
          git fetch --prune --unshallow
          git fetch --depth=1 origin +refs/tags/*:refs/tags/*
          VERSION=$(uvx hatch version | sed 's/\.dev.*//')
          echo "VERSION=$VERSION" >>"$GITHUB_OUTPUT"
          echo "VERSION=$VERSION"

      - name: Create Release Tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.email "admin@getubo.com"
          git config --local user.name "Ubo Admin"
          git tag -a "v${{ steps.extract-version.outputs.VERSION }}" -m "Release v${{ steps.extract-version.outputs.VERSION }}"
          git push origin "v${{ steps.extract-version.outputs.VERSION }}"
